nelmio_api_doc:
    documentation:
        info:
            title: API Foodtruck Hooly Society
            description: Mise a disposition par la société Hooly d'emplacements pour accueillir des foodtrucks sur ses différents campus.
            version: 1.0.0
    areas: # to filter documented areas
        path_patterns:
            - ^/api(?!/doc$) # Accepts routes under /api except /api/doc